db:
  image: postgres
  ports:
    - "5432"
web:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - .:/t2pay
  ports:
    - "3000:3000"
    - "8545:8545" #コンテナとホストのポート番号の対応を追加
  links:
    - db
  volumes_from:
    - bundle
  environment:
    - DB_USERNAME=postgres
    - DB_PASSWORD=
    - DB_HOST=db
bundle:
  image: t2pay_web
  volumes:
    - /bundle
